<?
    const ALL_PICTURES = 80;
    const PAINTED_MARKER = 23;
    const PAINTED_PENCIL = 40;
    const PAINTED_PAINTS = ALL_PICTURES - (PAINTED_MARKER + PAINTED_PENCIL);

    echo PAINTED_PAINTS;

?>