<?php
/** @var \App\Model\User $user */

use App\Model\User;

$user = $this->user
?>

<style>
    li{
        list-style: none;
    }

    ul{
        margin: 0;
        padding: 0;
    }

    .blog-page{
        width: 30%;
    }

    .blog-form{
        display: flex;
        flex-direction: column;
        gap: 20px;
    }

    .blog-form__text{
        width: 100%;
        height: 200px;
        resize: none;
        outline: none;
        padding: 10px;
    }

    .blog-form__buttons{
        display: flex;
        justify-content: space-between;
    }

    .blog-list{
        display: flex;
        flex-direction: column;
        gap: 20px;
    }

    .blog-list__item{
        border: 1px solid black;
        border-radius: 8px;
    }

    .blog-list__form{
        display: flex;
        padding: 10px;
    }

    .blog-list__item--delete{
        color: red;
        font-weight: bold;
        font-size: 26px;
        cursor: pointer;
        align-self: center;
        border: 0;
        background: none;
    }

    .blog-list__item--inner{
        width: 100%;
        display: flex;
        flex-direction: column;
        margin: 10px;
        gap: 10px;
    }

    .blog-list__image{
        width: 53px;
    }

    .blog-list__content{
        display: flex;
        align-items: center;
    }

    .blog-list__item--date{
        text-align: right;
    }

    .blog-list__item--text{
        word-break: break-all;
    }
</style>

<div class="blog-page">
    <form class="blog-form" action="/blog/add" method="post" enctype="multipart/form-data">
        <textarea class="blog-form__text" minlength="4" name="text" placeholder="Введите текст"></textarea>
        <div class="blog-form__buttons">
            <input class="blog-form__btn left" type="file" name="file" accept="image/png, image/gif, image/jpeg">
            <button class="blog-form__btn right" type="submit">Отправить</button>
        </div>
    </form>
        <ul class="blog-list">
            <?php foreach ($this->messages as $value): ?>
                <?php $owner = User::getById($value['owner_id']); ?>
               <li class="blog-list__item">
                   <form class="blog-list__form" action="/blog/delete" method="post">
                       <?php if($value['image']): ?>
                           <div class="blog-list__content">
                               <img class="blog-list__image" src="<?="../image/" . $value['image']?>">
                           </div>
                       <?php endif;?>
                       <div class="blog-list__item--inner">
                           <span class="blog-list__item--name"><?=$owner->name?></span>
                           <div class="blog-list__item--text"><?=$value['text']?></div>
                           <span class="blog-list__item--date"><?=$value['created_at']?></span>
                       </div>
                       <?php if($user->role === ADMIN_ROLE):?>
                           <input style="display: none;" name="id" value="<?=$value['id']?>">
                           <button class="blog-list__item--delete" type="submit">&times;</button>
                       <?php endif?>
                   </form>
               </li>
            <?php endforeach;?>
        </ul>
</div>
